Repository instedd/surveda, pull requests merged in 2021-11, with the labels that each got.

#1983 Attempt to silence race condition on audio play/load/pause
  web/static/js/components/simulation/VoiceWindow.jsx
Labels: bug, frontend

#1993 Add restart button to simulator ended/expired notification
  locales/template/translation.json
  locales/translations/es.json
  locales/translations/fr.json
  web/static/css/_buttons.scss
  web/static/js/components/simulation/QuestionnaireSimulation.jsx
  web/static/js/components/ui/MainAction.jsx
Labels: frontend

#1996 Fix: optimize audios' uuid column
  priv/repo/migrations/20211125141835_optimize_audios_uuid.exs
Labels: bug

#2001 Fix local setup documentation
  README.md
  docs/dev-setup-local.md
Labels: enhancement
