Repository instedd/surveda, pull requests merged in 2021-12, with the labels that each got.

#1994 Create enums for Respondent state & disposition
  lib/ask/ecto_types/steps.ex
  lib/ask/runtime/broker.ex
  lib/ask/runtime/flow.ex
  lib/ask/runtime/nuntium_channel.ex
  lib/ask/runtime/panel_survey.ex
  lib/ask/runtime/questionnaire_simulator.ex
  lib/ask/runtime/respondent_group_action.ex
  lib/ask/runtime/session.ex
  lib/ask/runtime/survey.ex
  lib/ask/runtime/survey_logger.ex
  priv/repo/migrations/20170412201505_migrate_session_to_current_mode.exs
  priv/repo/migrations/20200408144038_remove_respondent_stalled_state.exs
  test/controllers/mobile_survey_controller_test.exs
  test/controllers/oauth_client_controller_test.exs
  test/controllers/respondent_group_controller_test.exs
  test/controllers/survey_controller_test.exs
  test/lib/runtime/broker_test.exs
  test/lib/runtime/flow_test.exs
  test/lib/runtime/questionnaire_simulator_test.exs
  test/lib/runtime/session_test.exs
  test/lib/runtime/survey_test.exs
  test/lib/runtime/verboice_channel_test.exs
  test/support/test_helpers.ex
  test/survey_canceller/survey_canceller_test.exs
  web/controllers/mobile_survey_controller.ex
  web/controllers/respondent_controller.ex
  web/controllers/survey_respondents_canceller.ex
  web/models/questionnaire.ex
  web/models/respondent.ex
  web/models/respondent_disposition_history.ex
  web/models/respondent_stats.ex
  web/models/survey.ex
Labels: enhancement, technical-debt :octocat:

#2005 Replace occurrence with wave
  lib/ask/runtime/panel_survey.ex
  lib/ask/runtime/survey_action.ex
  test/controllers/folder_controller_test.exs
  test/controllers/panel_survey_controller_test.exs
  test/controllers/survey_controller_test.exs
  test/lib/runtime/panel_survey_test.exs
  test/lib/runtime/survey_action_test.exs
  test/support/test_helpers.ex
  web/controllers/panel_survey_controller.ex
  web/controllers/survey_controller.ex
  web/models/panel_survey.ex
  web/models/survey.ex
  web/router.ex
  web/static/js/actions/survey.js
  web/static/js/api.js
  web/static/js/components/surveys/PanelSurveyShow.jsx
  web/static/js/components/surveys/SurveyForm.jsx
  web/static/js/components/surveys/SurveyIndex.jsx
  web/static/js/components/surveys/SurveyShow.jsx
  web/views/panel_survey_view.ex
Labels: technical-debt :octocat:

#2013 Fix: cache-control header for AudioController and AudioDeliveryController
  test/controllers/audio_controller_test.exs
  test/controllers/audio_delivery_controller_test.exs
  web/controllers/audio_controller.ex
  web/controllers/audio_delivery_controller.ex
  web/web.ex
Labels: bug

#2015 Fix: can't export some questionnaires as CSV
  web/static/js/components/questionnaires/QuestionnaireMenu.jsx
Labels: bug

#1989 Sandbox: add waveform to IVR simulator
  web/static/css/_quex-simulation.scss
  web/static/js/components/simulation/VoiceWindow.jsx
Labels: enhancement, frontend

#2006 Sandbox: add chat history to IVR simulator responses
  lib/ask/runtime/questionnaire_simulator.ex
  test/controllers/questionnaire_controller_test.exs
  web/static/css/_quex-simulation.scss
  web/static/js/components/simulation/ChatWindow.jsx
  web/static/js/components/simulation/MessagesList.jsx
  web/static/js/components/simulation/QuestionnaireSimulation.jsx
  web/static/js/components/simulation/VoiceWindow.jsx
  web/views/questionnaire_view.ex
Labels: enhancement

#2018 Fix: IVR crash on quex step with refusal disabled
  lib/ask/runtime/step.ex
  test/lib/runtime/flow_test.exs
Labels: bug

#2020 Fix: performance issue in RespondentGroupAction.remove_duplicates_with_respect_to/2
  lib/ask/runtime/respondent_group_action.ex
  priv/repo/migrations/20211213094856_add_index_to_respondents_canonical_phone_numbers.exs
Labels: bug
